# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: '../../Dockerfile'
  # command that will be run by the container (instanciated from the image built from our dockerfile that give just above)
  entrypoint: python
  args: ["/python_app/source/app.py", "${{ inputs.who-to-greet }}"]
