name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: 'Dockerfile'
    steps:
      - name: Check for dockerenv file
        run: (ls) || (echo No dockerenv)
