on: [push]

jobs:
  unit_test_job:
    runs-on: ubuntu-latest
    name: unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: tests
        uses: ./.github/pytest_action/ # Uses action in pytest_action
        id: tests

